using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroKit.Messaging.EntityFrameworkCore;

/// <summary>
/// EF Core entity configuration for <see cref="InboxMessage"/>.
/// Apply via <see cref="ModelBuilderExtensions.ApplyMessagingConfiguration"/>.
/// </summary>
/// <remarks>
/// Two mapping decisions here are load-bearing rather than cosmetic. Getting either wrong
/// silently removes a correctness guarantee the processor claims to provide, which is why they
/// are configured centrally instead of being left to each consumer.
/// </remarks>
public sealed class InboxMessageConfiguration : IEntityTypeConfiguration<InboxMessage>
{
    /// <inheritdoc/>
    public void Configure(EntityTypeBuilder<InboxMessage> builder)
    {
        builder.ToTable("InboxMessages");

        // DECISION 1 — single-column surrogate primary key.
        //
        // The logical key stays (MessageId, ConsumerType) and remains the dedup gate through
        // the unique index below: a duplicate insert still violates it, so ingestion behaviour
        // is unchanged. What the surrogate buys is a batch claim expressible as ONE bounded
        // list. Filtering an UPDATE with two Contains over a compound key selects the cross
        // product of both lists, not the candidate pairs — it claims rows nobody chose and can
        // exceed batchSize several times over.
        builder.HasKey(m => m.RowId);

        // Assigned by the writer, never generated by the provider: a row carries its identity
        // before it is saved, which is what lets the publisher build a batch in memory.
        builder.Property(m => m.RowId)
            .ValueGeneratedNever();

        // The dedup gate. Unique, and the sole authority on deduplication — EfInboxStore.AddAsync
        // recognises a redelivery by the violation this raises, never by decoding an error code.
        builder.HasIndex(m => new { m.MessageId, m.ConsumerType })
            .IsUnique()
            .HasDatabaseName("UX_InboxMessages_MessageId_ConsumerType");

        // DECISION 2 — ClaimToken is a concurrency token.
        //
        // This is what makes IInboxSettlementStore.StageProcessedAsync safe. Without it, the
        // UPDATE that SaveChanges emits carries only the primary key, so a processor whose lease
        // expired mid-handler would overwrite the processor that legitimately re-claimed the
        // row. With it, EF puts the original token in the WHERE clause, the update matches zero
        // rows, and the resulting concurrency exception rolls back the handler transaction —
        // mark and side effects together.
        //
        // Removing this line breaks no test that does not exercise concurrency, and it silently
        // reintroduces a lost update. Treat it as part of the contract.
        builder.Property(m => m.ClaimToken)
            .IsConcurrencyToken();

        builder.Property(m => m.MessageId)
            .HasConversion(new ValueConverter<MessageId, Guid>(
                v => v.Value,
                v => new MessageId(v)));

        builder.Property(m => m.ConsumerType)
            .IsRequired()
            .HasMaxLength(512);

        builder.Property(m => m.TenantId)
            .HasMaxLength(256);
        // TenantId is intentionally optional (no IsRequired) — Messaging must operate
        // without Multitenancy per ADR-EXEC-001; host enforces TenantId when needed.

        builder.Property(m => m.EventType)
            .IsRequired()
            .HasMaxLength(512);

        builder.Property(m => m.Payload)
            .IsRequired();

        builder.Property(m => m.Status)
            .IsRequired()
            .HasConversion<string>()
            .HasMaxLength(32);

        builder.Property(m => m.ErrorMessage)
            .HasMaxLength(2048);

        builder.Property(m => m.CorrelationId)
            .HasConversion(new ValueConverter<CorrelationId?, Guid?>(
                v => v == null ? null : v.Value,
                v => v == null ? null : new CorrelationId(v.Value)));

        builder.Property(m => m.CausationId)
            .HasConversion(new ValueConverter<CausationId?, Guid?>(
                v => v == null ? null : v.Value,
                v => v == null ? null : new CausationId(v.Value)));

        // No HasQueryFilter — infrastructure table, read cross-tenant by processors (ADR-MSG-002).

        // OccurredOnUtc carries the producer's business timeline and is DELIBERATELY unindexed
        // and unordered on. It is caller-supplied at the far end of a wire — an optional
        // parameter of a public publish method — so a backdated value ordered on here would jump
        // the whole queue and keep jumping it. That is the defect the outbox claim left behind
        // when it moved its sort key to CreatedAtUtc; adding this column to IX_InboxMessages_
        // Processable, or to the store's OrderBy, reintroduces it on the inbox. Pinned by
        // TheProcessableIndex_SortsOnReceivedAtUtc_AndExcludesOccurredOnUtc.

        // Claim path: candidates are the non-dead-lettered rows ordered by ReceivedAtUtc.
        // Indexes are deliberately UNFILTERED. A partial index (WHERE dead_lettered = false,
        // WHERE claim_token IS NOT NULL) would keep both smaller as processed rows accumulate,
        // but HasFilter takes provider-specific SQL and this is the provider-neutral package.
        // A consumer writing their own DDL should prefer the partial form.
        builder.HasIndex(m => new { m.DeadLettered, m.Status, m.NextRetryAtUtc, m.ReceivedAtUtc })
            .HasDatabaseName("IX_InboxMessages_Processable");

        // Read-back by token, the third step of the claim.
        builder.HasIndex(m => m.ClaimToken)
            .HasDatabaseName("IX_InboxMessages_ClaimToken");

        // Retention: DeleteProcessedAsync filters on (TenantId, ProcessedAtUtc).
        builder.HasIndex(m => new { m.TenantId, m.ProcessedAtUtc })
            .HasDatabaseName("IX_InboxMessages_TenantId_ProcessedAt");
    }
}
