using System.Threading;

namespace MicroKit.Logging.Generators;

/// <summary>
/// Incremental source generator that produces a <c>BeginLogScope(ILogger logger)</c> method
/// for types decorated with <c>[MicroKitLogScope]</c>.
/// </summary>
[Generator]
public sealed class LogScopeGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "MicroKit.Logging.MicroKitLogScopeAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, ct) => BuildModel(ctx, ct))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, static (ctx, model) =>
        {
            if (model is null) return;
            ctx.AddSource($"{model.TypeName}.g.cs", SourceText.From(Emit(model), Encoding.UTF8));
        });
    }

    private static LogScopeModel? BuildModel(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        // The type must be declared partial so we can add a method to it
        if (!IsPartial(context.TargetNode))
            return null;

        var isRecord = typeSymbol.IsRecord;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var propertiesBuilder = ImmutableArray.CreateBuilder<LogPropertyModel>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is not IPropertySymbol property) continue;
            if (property.IsStatic) continue;
            if (property.IsIndexer) continue;
            if (property.DeclaredAccessibility != Accessibility.Public) continue;
            if (property.GetMethod is null) continue;

            var isNullable = property.NullableAnnotation == NullableAnnotation.Annotated
                || property.Type.IsValueType == false;

            propertiesBuilder.Add(new LogPropertyModel(property.Name, isNullable));
        }

        if (propertiesBuilder.Count == 0)
            return null;

        return new LogScopeModel(
            TypeName: typeSymbol.Name,
            Namespace: ns,
            IsRecord: isRecord,
            Properties: new EquatableArray<LogPropertyModel>(propertiesBuilder.ToImmutable()));
    }

    private static bool IsPartial(SyntaxNode node)
    {
        if (node is ClassDeclarationSyntax classDecl)
        {
            foreach (var modifier in classDecl.Modifiers)
            {
                if (modifier.IsKind(SyntaxKind.PartialKeyword))
                    return true;
            }
        }
        else if (node is RecordDeclarationSyntax recordDecl)
        {
            foreach (var modifier in recordDecl.Modifiers)
            {
                if (modifier.IsKind(SyntaxKind.PartialKeyword))
                    return true;
            }
        }

        return false;
    }

    private static string Emit(LogScopeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        var typeKind = model.IsRecord ? "record" : "class";
        sb.Append("partial ").Append(typeKind).Append(' ').AppendLine(model.TypeName);
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>Begins a structured log scope containing all properties of this instance.</summary>");
        sb.AppendLine("    public global::System.IDisposable BeginLogScope(");
        sb.AppendLine("        global::Microsoft.Extensions.Logging.ILogger logger) =>");
        sb.AppendLine("        logger.BeginScope(");
        sb.AppendLine("            new global::System.Collections.Generic.KeyValuePair<string, object?>[]");
        sb.AppendLine("            {");

        var properties = model.Properties.AsImmutableArray();
        foreach (var prop in properties)
        {
            sb.Append("                new(\"").Append(prop.Name).Append("\", (object?)this.").Append(prop.Name).AppendLine("),");
        }

        sb.AppendLine("            });");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
