namespace MicroKit.Auth.Jwt;

/// <summary>
/// Configuration for HMAC-SHA256 JWT validation and generation.
/// </summary>
/// <remarks>
/// <para>
/// Phase 1 scope: HS256 (HMAC-SHA256) only. RS256 and ES256 via JWKS are deferred
/// to provider packages (<c>MicroKit.Auth.Supabase</c>, <c>MicroKit.Auth.OpenIdConnect</c>).
/// See ADR-AUTH-007 for the full rationale.
/// </para>
/// <para>
/// Register via <see cref="ServiceCollectionExtensions.AddMicroKitAuthJwt"/>, which validates
/// these options eagerly at startup and throws <see cref="InvalidOperationException"/> for
/// any invalid configuration before the application begins serving requests.
/// </para>
/// <para>
/// <b>Immutability:</b> After the options instance is registered as a singleton by
/// <see cref="ServiceCollectionExtensions.AddMicroKitAuthJwt"/>, treat it as immutable.
/// The mutable setters exist solely to support the <c>Action&lt;JwtOptions&gt;</c>
/// configuration pattern used at startup — mutating the instance post-registration has
/// undefined behaviour and will not be honoured by already-constructed services.
/// </para>
/// </remarks>
public sealed record JwtOptions
{
    /// <summary>
    /// The expected token issuer (<c>iss</c> claim). Validated on every incoming token.
    /// Must not be null or whitespace.
    /// </summary>
    public string Issuer { get; set; } = string.Empty;

    /// <summary>
    /// The expected token audience (<c>aud</c> claim). Validated on every incoming token.
    /// Must not be null or whitespace.
    /// </summary>
    public string Audience { get; set; } = string.Empty;

    /// <summary>
    /// The HMAC-SHA256 signing secret. Must be at least 32 UTF-8 bytes.
    /// Never hardcode this value in source — load from environment variables or a secrets
    /// manager at startup.
    /// </summary>
    public string Secret { get; set; } = string.Empty;

    /// <summary>
    /// Lifetime applied to tokens generated by <see cref="IJwtTokenGenerator"/>.
    /// Defaults to one hour.
    /// </summary>
    public TimeSpan Expiry { get; set; } = TimeSpan.FromHours(1);

    /// <summary>
    /// Maximum allowed clock drift when validating the <c>exp</c> and <c>nbf</c> claims.
    /// Defaults to five minutes.
    /// </summary>
    public TimeSpan ClockSkew { get; set; } = TimeSpan.FromMinutes(5);
}
