using BenchmarkDotNet.Attributes;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace MicroKit.Logging.PerformanceTests;

/// <summary>
/// Measures the hot-path cost of <see cref="ILogScopeFactory.BeginOperationScope"/> under
/// varying enricher loads. Covers the full scope lifecycle: creation, context propagation,
/// enrichment dispatch, and disposal.
/// </summary>
[MemoryDiagnoser]
[MinColumn, MaxColumn]
public class EnrichmentPipelineBenchmark
{
    private ServiceProvider _noEnrichers = null!;
    private ServiceProvider _oneEnricher = null!;
    private ILogScopeFactory _factoryNoEnrichers = null!;
    private ILogScopeFactory _factoryOneEnricher = null!;

    [GlobalSetup]
    public void Setup()
    {
        _noEnrichers = BuildProvider();
        _oneEnricher = BuildProvider(new NoOpEnricher());
        _factoryNoEnrichers = _noEnrichers.GetRequiredService<ILogScopeFactory>();
        _factoryOneEnricher = _oneEnricher.GetRequiredService<ILogScopeFactory>();
    }

    [GlobalCleanup]
    public void Cleanup()
    {
        _noEnrichers.Dispose();
        _oneEnricher.Dispose();
    }

    /// <summary>Baseline — propagated correlation ID, no enrichers.</summary>
    [Benchmark(Baseline = true)]
    public void BeginScope_Propagated_NoEnrichers()
    {
        using var scope = _factoryNoEnrichers.BeginOperationScope("b3ac68f1-9c2e-4d8a-ae2e-1c2c4a7b3d1e");
    }

    /// <summary>Auto-generated correlation ID — exercises <c>CorrelationIdGenerator</c>.</summary>
    [Benchmark]
    public void BeginScope_AutoGenerated_NoEnrichers()
    {
        using var scope = _factoryNoEnrichers.BeginOperationScope();
    }

    /// <summary>One no-op enricher — measures pipeline dispatch overhead per enricher slot.</summary>
    [Benchmark]
    public void BeginScope_Propagated_OneEnricher()
    {
        using var scope = _factoryOneEnricher.BeginOperationScope("b3ac68f1-9c2e-4d8a-ae2e-1c2c4a7b3d1e");
    }

    private static ServiceProvider BuildProvider(params ILogEnricher[] enrichers)
    {
        var services = new ServiceCollection();
        // Register open-generic NullLogger<T> without pulling in the full Logging package.
        services.AddSingleton(typeof(ILogger<>), typeof(NullLogger<>));
        services.AddMicroKitLogging();
        foreach (var enricher in enrichers)
            services.AddSingleton<ILogEnricher>(enricher);
        return services.BuildServiceProvider();
    }

    private sealed class NoOpEnricher : ILogEnricher
    {
        public int Order => 0;
        public void Enrich(ILogEnrichmentContext context) { }
    }
}
