namespace MicroKit.Messaging;

/// <summary>
/// Represents an inbound message stored in the transactional inbox, which deduplicates
/// redelivered integration events and records that a consumer has handled one.
/// </summary>
/// <remarks>
/// <para>
/// The compound key <c>(MessageId, ConsumerType)</c> is the authoritative deduplication
/// guard, enforced by a unique database constraint. A single envelope may be consumed
/// by multiple handlers independently — each gets its own <see cref="InboxMessage"/> row.
/// </para>
/// <para>
/// <b>The primary key is <see cref="RowId"/>, not that compound key.</b> The compound key
/// remains the dedup gate through a unique index, so ingestion behaviour is unchanged; what the
/// surrogate buys is a batch claim expressible as ONE bounded list. Filtering an <c>UPDATE</c>
/// with two <c>Contains</c> over a compound key selects the cross product of both lists rather
/// than the candidate pairs, which claims rows nobody chose and can exceed the batch size
/// several times over.
/// </para>
/// <para>
/// <c>InboxMessage</c> is a <c>sealed class</c> because EF Core change tracking
/// requires mutable <c>{ get; set; }</c> properties.
/// </para>
/// <para>
/// <c>TenantId</c> is optional. <see langword="null"/> in single-tenant deployments.
/// </para>
/// </remarks>
public sealed class InboxMessage
{
    /// <summary>
    /// Gets or sets the single-column surrogate primary key.
    /// </summary>
    /// <remarks>
    /// Assigned by the writer at construction and never generated by the database, so a row
    /// carries its identity before it is saved. It is infrastructure, never a domain identifier,
    /// and is deliberately a plain <see cref="Guid"/>: a strongly-typed id would buy nothing and
    /// cost a value converter on the claim path, which is the hottest query in the module.
    /// </remarks>
    public Guid RowId { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Gets or sets the identifier of the original message.
    /// Part 1 of the compound deduplication key — paired with <see cref="ConsumerType"/>.
    /// </summary>
    public MessageId MessageId { get; set; } = null!;

    /// <summary>
    /// Gets or sets the assembly-qualified CLR type name of the handler consuming this message
    /// (e.g. <c>"MyApp.Orders.OrderPlacedHandler, MyApp"</c>).
    /// Part 2 of the compound deduplication key.
    /// </summary>
    public string ConsumerType { get; set; } = null!;

    /// <summary>
    /// Gets or sets the identifier of the tenant this message belongs to.
    /// Optional. Null in single-tenant deployments.
    /// </summary>
    public string? TenantId { get; set; }

    /// <summary>
    /// Gets or sets the assembly-qualified CLR type name of the integration event.
    /// </summary>
    public string EventType { get; set; } = null!;

    /// <summary>Gets or sets the JSON-serialized integration event payload.</summary>
    public string Payload { get; set; } = null!;

    /// <summary>Gets or sets the current lifecycle state of this inbox message.</summary>
    public InboxMessageStatus Status { get; set; }

    /// <summary>Gets or sets the number of failed handler invocation attempts.</summary>
    public int RetryCount { get; set; }

    /// <summary>Gets or sets the UTC time at which this message was received.</summary>
    public DateTimeOffset ReceivedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets the UTC time at which the handler completed successfully.
    /// <see langword="null"/> while pending or processing.
    /// </summary>
    public DateTimeOffset? ProcessedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets the UTC time until which this message is locked by the processor
    /// currently handling it. <see langword="null"/> when no lease is held.
    /// </summary>
    public DateTimeOffset? LockedUntilUtc { get; set; }

    /// <summary>
    /// Gets or sets the ownership token stamped by the claim that reserved this row.
    /// <see langword="null"/> when no claim is held.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The token does two jobs. As a <b>fence</b>, every terminal write filters on it, so a
    /// processor whose lease expired mid-handler matches zero rows instead of overwriting the
    /// processor that legitimately re-claimed the row.
    /// </para>
    /// <para>
    /// As a <b>settled marker</b>, a committed handler transaction leaves it null, so every
    /// deferred write for that row filters to zero rows and becomes a no-op. That is what makes
    /// the shutdown path correct: a release issued while the host is stopping cannot undo a
    /// success that already committed. It is an invariant, not a happy accident.
    /// </para>
    /// <para>
    /// It must be mapped as an EF concurrency token — see <c>InboxMessageConfiguration</c>.
    /// Without that, the <c>UPDATE</c> emitted by <c>SaveChanges</c> carries the primary key
    /// alone and the token is checked at read time only, which is precisely the lost update it
    /// exists to prevent.
    /// </para>
    /// </remarks>
    public Guid? ClaimToken { get; set; }

    /// <summary>
    /// Gets or sets the last error message recorded during a failed handler invocation.
    /// <see langword="null"/> when no error has occurred.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Gets or sets the earliest UTC time at which this message becomes eligible for
    /// re-processing after a transient handler failure. <see langword="null"/> until the
    /// first failure.
    /// </summary>
    /// <remarks>
    /// Computed by <c>InboxProcessor</c>, not by the store: back-off is retry policy, not
    /// persistence, and it must be unit-testable without a database. The formula is full jitter
    /// over an exponential ceiling — <c>Uniform(0, min(2^RetryCount s, MaxRetryBackoff))</c> —
    /// matching the outbox. A deterministic curve would make every message that failed together,
    /// which is exactly what an outage produces, retry together on every subsequent attempt.
    /// </remarks>
    public DateTimeOffset? NextRetryAtUtc { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this message has been permanently
    /// dead-lettered (i.e. <c>MaxRetries</c> was exceeded). When <see langword="true"/>,
    /// <see cref="Status"/> is <see cref="InboxMessageStatus.Failed"/> and no further
    /// retry will be attempted. Symmetric with <c>OutboxMessage.DeadLettered</c>.
    /// </summary>
    public bool DeadLettered { get; set; }

    /// <summary>
    /// Gets or sets the correlation identifier propagated from the originating message chain.
    /// <see langword="null"/> when no correlation context was available on the inbound message.
    /// </summary>
    public CorrelationId? CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the causation identifier recording which message triggered this one.
    /// <see langword="null"/> for root events.
    /// </summary>
    public CausationId? CausationId { get; set; }
}
